import "./globals.css";
// import Providers from "app/components/Providers";
import Header from "app/components/Header";

export const metadata = {
  title: "Saul News",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* </Providers>
        <Providers> */}
      <body>
        <div className="bg-gray-100 dark:bg-zinc-900 transition-all duration-700">
          <Header />
          <div className="max-w-6xl mx-auto">{children}</div>
        </div>
      </body>
    </html>
  );
}
